# Generated by Django 5.0.6 on 2024-08-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_is_bankrupt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
    ]
